version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: silapor-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kelompok-7
      POSTGRES_DB: silaporcloud
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
